### ISSUE TITLE
OK in library code?

### ISSUE THREAD

**Issue by isovector** [well-typed/recover-rtti#25]
I've been using `anythingToString` for a `Show` instance for a gnarly, existentially packed type. It's been really lovely, and is significantly better than any instance I could possibly write by hand.

I'd like to ship the library with the `Show` instance but am unsure how kosher this idea is. Would love some guidance here! Thanks!

**Comment by edsko** [comment]
Hmm. I think it's _probably_ ok. The version bound on `recover-rtti` should ensure that it won't crash horribly with unsupported versions of ghc. Moreover, later versions of `ghc` _probably_ won't change the heap representation to such a extent that `recover-rtti` could not be updated for them. 

But.. it remains true of course that `recover-rtti` does some things that Haskell code should really not be doing :) It's not intended for production usage. So.. _probably_ ok is about the best I can do I think :)

**Comment by isovector** [comment]
Thanks! Maybe I'll hide it behind a flag.
