### ISSUE TITLE
Lower bound on unordered-containers

### ISSUE THREAD

**Issue by isovector** [well-typed/recover-rtti#8]
Currently there is no lower-bound on `unordered-containers`, but it looks like it should be `0.2.12.0`

**Comment by edsko** [comment]
Yes, in my rush to get a bugfix release out I forgot to add some lower bounds. Will fix, thanks! :)

**Comment by isovector** [comment]
I used `recover-rtti` today for the first time and WOW is this thing _amazing._ THANK YOU SO MUCH for writing it.

**Comment by edsko** [comment]
That's great to hear! :-) Appreciate that :)

**Comment by isovector** [comment]
I'd love this to get fixed; every few weeks I try to use `recover-rtti` and have to jump through a bunch of hoops to get it compiling.

**Comment by edsko** [comment]
Done! https://hackage.haskell.org/package/recover-rtti-0.4.0.0

Apologies for the delay, didn't realize it was causing hassle. 0.4 has a bunch of backwards incompatible changes, but if you only use `anythingToString` you should be unaffected.

**Comment by isovector** [comment]
Thanks so much!
